# Use official Airflow image
FROM apache/airflow:2.9.1

# Switch to root user to make changes
USER root

# Create necessary directories and set permissions
RUN mkdir -p /opt/airflow/logs && \
    chown -R airflow /opt/airflow/logs

# Switch to airflow user (important!)
USER airflow

# Copy Python dependencies
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt
